services:
  postgres:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_DB: "cippa-bot-db"
      POSTGRES_USER: "cippa-bot-user"
      POSTGRES_PASSWORD: "a0c7f6151d42e9f804c6"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "9007:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smart-toy-user -d smart-toy-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G

volumes:
  pgdata:
